### ISSUE TITLE
Format the output of `bee status` command on empty DB

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/b#337]
If you run the `bee status` command on a Backdrop setup with an empty DB it gives:

```php
alan@last-web:/var/www/html/docroot$ bee status
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.state' doesn't exist in /var/www/html/docroot/core/includes/database/database.inc:2285
Stack trace:
#0 /var/www/html/docroot/core/includes/database/database.inc(2285): PDOStatement->execute(Array)
#1 /var/www/html/docroot/core/includes/database/database.inc(717): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/html/docroot/core/includes/database/database.inc(2468): DatabaseConnection->query('SELECT name, va...', Array, Array)
#3 /home/alan/bin/bee/commands/status.bee.inc(101): db_query('SELECT name, va...')
#4 /home/alan/bin/bee/includes/command.inc(91): status_bee_callback(Array, Array)
#5 /home/alan/bin/bee/bee.php(30): bee_process_command()
#6 {main}
  thrown in /var/www/html/docroot/core/includes/database/database.inc on line 2285

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.state' doesn't exist in /var/www/html/docroot/core/includes/database/database.inc:2285
Stack trace:
#0 /var/www/html/docroot/core/includes/database/database.inc(2285): PDOStatement->execute(Array)
#1 /var/www/html/docroot/core/includes/database/database.inc(717): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/html/docroot/core/includes/database/database.inc(2468): DatabaseConnection->query('SELECT name, va...', Array, Array)
#3 /home/alan/bin/bee/commands/status.bee.inc(101): db_query('SELECT name, va...')
#4 /home/alan/bin/bee/includes/command.inc(91): status_bee_callback(Array, Array)
#5 /home/alan/bin/bee/bee.php(30): bee_process_command()
#6 {main}
  thrown in /var/www/html/docroot/core/includes/database/database.inc on line 2285
alan@last-web:/var/www/html/docroot$ 
```

I believe this could caught early to output some human-friendly message.

**Comment by yorkshire-pudding** [comment]
Hi @alanmels - thanks for reporting. I agree that we should try to handle this scenario better.

**Comment by yorkshire-pudding** [comment]
Hi @alanmels - thanks again for picking up on this. I've added some basic handling and messaging around this in #340 . Let me know what you think.
